### ISSUE TITLE
Parsenal quits on null plugin tags

### ISSUE THREAD

**Issue by smittix** [lorentzenman/parsenal#1]
Great script, 

I parsed a large Nessus file but because a few issues had null plugin tags (<plugin_output></plugin_output>) the script failed.

After finding and replacing all null tags with an actual value, the script worked perfectly and dumped me into a an interactive SQL console.

Great work, this is definitely one that's going to be kept in my 'Tools' folder on my build.

**Comment by lorentzenman** [comment]
Thanks for this. I have recently pushed a new version and changed the XML parser. This work has solved the parsing issue when you hit a declared tag without any text value and has made the tool more memory efficient as it parses the tree.

Cheers
